/*
 * generated by Xtext 2.24.0
 */
package tools.vitruv.dsls.reactions.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractReactionsLanguageScopeProvider extends XbaseBatchScopeProvider {
}
