/**
 * generated by Xtext 2.24.0
 */
package tools.vitruv.dsls.reactions.language.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import tools.vitruv.dsls.common.elements.MetaclassReference;

import tools.vitruv.dsls.reactions.language.CreateModelElement;
import tools.vitruv.dsls.reactions.language.ExecutionCodeBlock;
import tools.vitruv.dsls.reactions.language.LanguagePackage;

import tools.vitruv.dsls.reactions.language.toplevelelements.impl.ActionStatementImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Create Model Element</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.reactions.language.impl.CreateModelElementImpl#getName <em>Name</em>}</li>
 *   <li>{@link tools.vitruv.dsls.reactions.language.impl.CreateModelElementImpl#getElementType <em>Element Type</em>}</li>
 *   <li>{@link tools.vitruv.dsls.reactions.language.impl.CreateModelElementImpl#getInitializationBlock <em>Initialization Block</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CreateModelElementImpl extends ActionStatementImpl implements CreateModelElement
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getElementType() <em>Element Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElementType()
   * @generated
   * @ordered
   */
  protected MetaclassReference elementType;

  /**
   * The cached value of the '{@link #getInitializationBlock() <em>Initialization Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInitializationBlock()
   * @generated
   * @ordered
   */
  protected ExecutionCodeBlock initializationBlock;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CreateModelElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LanguagePackage.Literals.CREATE_MODEL_ELEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LanguagePackage.CREATE_MODEL_ELEMENT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MetaclassReference getElementType()
  {
    return elementType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetElementType(MetaclassReference newElementType, NotificationChain msgs)
  {
    MetaclassReference oldElementType = elementType;
    elementType = newElementType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LanguagePackage.CREATE_MODEL_ELEMENT__ELEMENT_TYPE, oldElementType, newElementType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setElementType(MetaclassReference newElementType)
  {
    if (newElementType != elementType)
    {
      NotificationChain msgs = null;
      if (elementType != null)
        msgs = ((InternalEObject)elementType).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LanguagePackage.CREATE_MODEL_ELEMENT__ELEMENT_TYPE, null, msgs);
      if (newElementType != null)
        msgs = ((InternalEObject)newElementType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LanguagePackage.CREATE_MODEL_ELEMENT__ELEMENT_TYPE, null, msgs);
      msgs = basicSetElementType(newElementType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LanguagePackage.CREATE_MODEL_ELEMENT__ELEMENT_TYPE, newElementType, newElementType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExecutionCodeBlock getInitializationBlock()
  {
    return initializationBlock;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInitializationBlock(ExecutionCodeBlock newInitializationBlock, NotificationChain msgs)
  {
    ExecutionCodeBlock oldInitializationBlock = initializationBlock;
    initializationBlock = newInitializationBlock;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LanguagePackage.CREATE_MODEL_ELEMENT__INITIALIZATION_BLOCK, oldInitializationBlock, newInitializationBlock);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInitializationBlock(ExecutionCodeBlock newInitializationBlock)
  {
    if (newInitializationBlock != initializationBlock)
    {
      NotificationChain msgs = null;
      if (initializationBlock != null)
        msgs = ((InternalEObject)initializationBlock).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LanguagePackage.CREATE_MODEL_ELEMENT__INITIALIZATION_BLOCK, null, msgs);
      if (newInitializationBlock != null)
        msgs = ((InternalEObject)newInitializationBlock).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LanguagePackage.CREATE_MODEL_ELEMENT__INITIALIZATION_BLOCK, null, msgs);
      msgs = basicSetInitializationBlock(newInitializationBlock, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LanguagePackage.CREATE_MODEL_ELEMENT__INITIALIZATION_BLOCK, newInitializationBlock, newInitializationBlock));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LanguagePackage.CREATE_MODEL_ELEMENT__ELEMENT_TYPE:
        return basicSetElementType(null, msgs);
      case LanguagePackage.CREATE_MODEL_ELEMENT__INITIALIZATION_BLOCK:
        return basicSetInitializationBlock(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LanguagePackage.CREATE_MODEL_ELEMENT__NAME:
        return getName();
      case LanguagePackage.CREATE_MODEL_ELEMENT__ELEMENT_TYPE:
        return getElementType();
      case LanguagePackage.CREATE_MODEL_ELEMENT__INITIALIZATION_BLOCK:
        return getInitializationBlock();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LanguagePackage.CREATE_MODEL_ELEMENT__NAME:
        setName((String)newValue);
        return;
      case LanguagePackage.CREATE_MODEL_ELEMENT__ELEMENT_TYPE:
        setElementType((MetaclassReference)newValue);
        return;
      case LanguagePackage.CREATE_MODEL_ELEMENT__INITIALIZATION_BLOCK:
        setInitializationBlock((ExecutionCodeBlock)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LanguagePackage.CREATE_MODEL_ELEMENT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case LanguagePackage.CREATE_MODEL_ELEMENT__ELEMENT_TYPE:
        setElementType((MetaclassReference)null);
        return;
      case LanguagePackage.CREATE_MODEL_ELEMENT__INITIALIZATION_BLOCK:
        setInitializationBlock((ExecutionCodeBlock)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LanguagePackage.CREATE_MODEL_ELEMENT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case LanguagePackage.CREATE_MODEL_ELEMENT__ELEMENT_TYPE:
        return elementType != null;
      case LanguagePackage.CREATE_MODEL_ELEMENT__INITIALIZATION_BLOCK:
        return initializationBlock != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //CreateModelElementImpl
