/**
 * generated by Xtext 2.24.0
 */
package tools.vitruv.dsls.reactions.language.impl;

import org.eclipse.emf.ecore.EClass;

import tools.vitruv.dsls.reactions.language.ElementCompoundChangeType;
import tools.vitruv.dsls.reactions.language.LanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Element Compound Change Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ElementCompoundChangeTypeImpl extends ElementChangeTypeImpl implements ElementCompoundChangeType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ElementCompoundChangeTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LanguagePackage.Literals.ELEMENT_COMPOUND_CHANGE_TYPE;
  }

} //ElementCompoundChangeTypeImpl
