/**
 * generated by Xtext 2.24.0
 */
package tools.vitruv.dsls.reactions.language.impl;

import org.eclipse.emf.ecore.EClass;

import tools.vitruv.dsls.reactions.language.ExecutionCodeBlock;
import tools.vitruv.dsls.reactions.language.LanguagePackage;

import tools.vitruv.dsls.reactions.language.toplevelelements.impl.CodeBlockImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Execution Code Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExecutionCodeBlockImpl extends CodeBlockImpl implements ExecutionCodeBlock
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExecutionCodeBlockImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LanguagePackage.Literals.EXECUTION_CODE_BLOCK;
  }

} //ExecutionCodeBlockImpl
