/**
 * generated by Xtext 2.24.0
 */
package tools.vitruv.dsls.reactions.language.impl;

import org.eclipse.emf.ecore.EClass;

import tools.vitruv.dsls.reactions.language.ExistingElementReference;
import tools.vitruv.dsls.reactions.language.LanguagePackage;

import tools.vitruv.dsls.reactions.language.toplevelelements.impl.CodeBlockImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Existing Element Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExistingElementReferenceImpl extends CodeBlockImpl implements ExistingElementReference
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExistingElementReferenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LanguagePackage.Literals.EXISTING_ELEMENT_REFERENCE;
  }

} //ExistingElementReferenceImpl
