/**
 * generated by Xtext 2.24.0
 */
package tools.vitruv.dsls.reactions.language.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.eclipse.xtext.common.types.TypesPackage;

import org.eclipse.xtext.xbase.XbasePackage;

import org.eclipse.xtext.xtype.XtypePackage;

import tools.vitruv.dsls.common.elements.ElementsPackage;

import tools.vitruv.dsls.reactions.language.ArbitraryModelChange;
import tools.vitruv.dsls.reactions.language.ConcreteModelChange;
import tools.vitruv.dsls.reactions.language.CorrespondingObjectCodeBlock;
import tools.vitruv.dsls.reactions.language.CreateCorrespondence;
import tools.vitruv.dsls.reactions.language.CreateModelElement;
import tools.vitruv.dsls.reactions.language.DeleteModelElement;
import tools.vitruv.dsls.reactions.language.ElementChangeType;
import tools.vitruv.dsls.reactions.language.ElementCompoundChangeType;
import tools.vitruv.dsls.reactions.language.ElementCreationAndInsertionChangeType;
import tools.vitruv.dsls.reactions.language.ElementCreationChangeType;
import tools.vitruv.dsls.reactions.language.ElementDeletionAndCreationAndReplacementChangeType;
import tools.vitruv.dsls.reactions.language.ElementDeletionAndRemovalChangeType;
import tools.vitruv.dsls.reactions.language.ElementDeletionChangeType;
import tools.vitruv.dsls.reactions.language.ElementExistenceChangeType;
import tools.vitruv.dsls.reactions.language.ElementInsertionAsRootChangeType;
import tools.vitruv.dsls.reactions.language.ElementInsertionChangeType;
import tools.vitruv.dsls.reactions.language.ElementInsertionInListChangeType;
import tools.vitruv.dsls.reactions.language.ElementReferenceChangeType;
import tools.vitruv.dsls.reactions.language.ElementRemovalAsRootChangeType;
import tools.vitruv.dsls.reactions.language.ElementRemovalChangeType;
import tools.vitruv.dsls.reactions.language.ElementRemovalFromListChangeType;
import tools.vitruv.dsls.reactions.language.ElementReplacementChangeType;
import tools.vitruv.dsls.reactions.language.ElementRootChangeType;
import tools.vitruv.dsls.reactions.language.ExecuteActionStatement;
import tools.vitruv.dsls.reactions.language.ExecutionCodeBlock;
import tools.vitruv.dsls.reactions.language.ExistingElementReference;
import tools.vitruv.dsls.reactions.language.InvariantViolationEvent;
import tools.vitruv.dsls.reactions.language.LanguageFactory;
import tools.vitruv.dsls.reactions.language.LanguagePackage;
import tools.vitruv.dsls.reactions.language.MatcherCheckStatement;
import tools.vitruv.dsls.reactions.language.ModelAttributeChange;
import tools.vitruv.dsls.reactions.language.ModelAttributeInsertedChange;
import tools.vitruv.dsls.reactions.language.ModelAttributeRemovedChange;
import tools.vitruv.dsls.reactions.language.ModelAttributeReplacedChange;
import tools.vitruv.dsls.reactions.language.ModelChange;
import tools.vitruv.dsls.reactions.language.ModelElementChange;
import tools.vitruv.dsls.reactions.language.ModelElementUsageChangeType;
import tools.vitruv.dsls.reactions.language.RemoveCorrespondence;
import tools.vitruv.dsls.reactions.language.RequireAbscenceOfModelElement;
import tools.vitruv.dsls.reactions.language.RetrieveManyModelElements;
import tools.vitruv.dsls.reactions.language.RetrieveModelElement;
import tools.vitruv.dsls.reactions.language.RetrieveModelElementType;
import tools.vitruv.dsls.reactions.language.RetrieveOneElementType;
import tools.vitruv.dsls.reactions.language.RetrieveOneModelElement;
import tools.vitruv.dsls.reactions.language.RetrieveOrRequireAbscenceOfModelElement;
import tools.vitruv.dsls.reactions.language.RoutineCallStatement;
import tools.vitruv.dsls.reactions.language.TagCodeBlock;
import tools.vitruv.dsls.reactions.language.Taggable;
import tools.vitruv.dsls.reactions.language.UpdateModelElement;

import tools.vitruv.dsls.reactions.language.toplevelelements.TopLevelElementsPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class LanguagePackageImpl extends EPackageImpl implements LanguagePackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass invariantViolationEventEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelChangeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass concreteModelChangeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelElementChangeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelAttributeChangeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass arbitraryModelChangeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass elementExistenceChangeTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelElementUsageChangeTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass elementCreationChangeTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass elementDeletionChangeTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass elementReferenceChangeTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass elementRootChangeTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass elementInsertionChangeTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass elementInsertionInListChangeTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass elementInsertionAsRootChangeTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass elementRemovalChangeTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass elementRemovalAsRootChangeTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass elementRemovalFromListChangeTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass elementReplacementChangeTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass elementCreationAndInsertionChangeTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass elementDeletionAndRemovalChangeTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass elementDeletionAndCreationAndReplacementChangeTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass elementChangeTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass elementCompoundChangeTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass retrieveOrRequireAbscenceOfModelElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass requireAbscenceOfModelElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass retrieveModelElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass retrieveModelElementTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass matcherCheckStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass routineCallStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass executeActionStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass createModelElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass deleteModelElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass updateModelElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass createCorrespondenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass removeCorrespondenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass taggableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass existingElementReferenceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass tagCodeBlockEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass correspondingObjectCodeBlockEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass executionCodeBlockEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelAttributeInsertedChangeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelAttributeRemovedChangeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelAttributeReplacedChangeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass retrieveOneModelElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass retrieveManyModelElementsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum retrieveOneElementTypeEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see tools.vitruv.dsls.reactions.language.LanguagePackage#eNS_URI
   * @see #init()
   * @generated
   */
  private LanguagePackageImpl()
  {
    super(eNS_URI, LanguageFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link LanguagePackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static LanguagePackage init()
  {
    if (isInited) return (LanguagePackage)EPackage.Registry.INSTANCE.getEPackage(LanguagePackage.eNS_URI);

    // Obtain or create and register package
    Object registeredLanguagePackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    LanguagePackageImpl theLanguagePackage = registeredLanguagePackage instanceof LanguagePackageImpl ? (LanguagePackageImpl)registeredLanguagePackage : new LanguagePackageImpl();

    isInited = true;

    // Initialize simple dependencies
    ElementsPackage.eINSTANCE.eClass();
    TopLevelElementsPackage.eINSTANCE.eClass();
    XtypePackage.eINSTANCE.eClass();
    XbasePackage.eINSTANCE.eClass();
    TypesPackage.eINSTANCE.eClass();

    // Create package meta-data objects
    theLanguagePackage.createPackageContents();

    // Initialize created meta-data
    theLanguagePackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theLanguagePackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(LanguagePackage.eNS_URI, theLanguagePackage);
    return theLanguagePackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInvariantViolationEvent()
  {
    return invariantViolationEventEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getInvariantViolationEvent_Violation()
  {
    return (EReference)invariantViolationEventEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModelChange()
  {
    return modelChangeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getConcreteModelChange()
  {
    return concreteModelChangeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModelElementChange()
  {
    return modelElementChangeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModelElementChange_ElementType()
  {
    return (EReference)modelElementChangeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModelElementChange_ChangeType()
  {
    return (EReference)modelElementChangeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModelAttributeChange()
  {
    return modelAttributeChangeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModelAttributeChange_Feature()
  {
    return (EReference)modelAttributeChangeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getArbitraryModelChange()
  {
    return arbitraryModelChangeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getElementExistenceChangeType()
  {
    return elementExistenceChangeTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModelElementUsageChangeType()
  {
    return modelElementUsageChangeTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getElementCreationChangeType()
  {
    return elementCreationChangeTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getElementDeletionChangeType()
  {
    return elementDeletionChangeTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getElementReferenceChangeType()
  {
    return elementReferenceChangeTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getElementReferenceChangeType_Feature()
  {
    return (EReference)elementReferenceChangeTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getElementRootChangeType()
  {
    return elementRootChangeTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getElementInsertionChangeType()
  {
    return elementInsertionChangeTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getElementInsertionInListChangeType()
  {
    return elementInsertionInListChangeTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getElementInsertionAsRootChangeType()
  {
    return elementInsertionAsRootChangeTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getElementRemovalChangeType()
  {
    return elementRemovalChangeTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getElementRemovalAsRootChangeType()
  {
    return elementRemovalAsRootChangeTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getElementRemovalFromListChangeType()
  {
    return elementRemovalFromListChangeTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getElementReplacementChangeType()
  {
    return elementReplacementChangeTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getElementCreationAndInsertionChangeType()
  {
    return elementCreationAndInsertionChangeTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getElementCreationAndInsertionChangeType_CreateChange()
  {
    return (EReference)elementCreationAndInsertionChangeTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getElementCreationAndInsertionChangeType_InsertChange()
  {
    return (EReference)elementCreationAndInsertionChangeTypeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getElementDeletionAndRemovalChangeType()
  {
    return elementDeletionAndRemovalChangeTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getElementDeletionAndRemovalChangeType_DeleteChange()
  {
    return (EReference)elementDeletionAndRemovalChangeTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getElementDeletionAndRemovalChangeType_RemoveChange()
  {
    return (EReference)elementDeletionAndRemovalChangeTypeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getElementDeletionAndCreationAndReplacementChangeType()
  {
    return elementDeletionAndCreationAndReplacementChangeTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getElementDeletionAndCreationAndReplacementChangeType_DeleteChange()
  {
    return (EReference)elementDeletionAndCreationAndReplacementChangeTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getElementDeletionAndCreationAndReplacementChangeType_CreateChange()
  {
    return (EReference)elementDeletionAndCreationAndReplacementChangeTypeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getElementDeletionAndCreationAndReplacementChangeType_ReplacedChange()
  {
    return (EReference)elementDeletionAndCreationAndReplacementChangeTypeEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getElementChangeType()
  {
    return elementChangeTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getElementCompoundChangeType()
  {
    return elementCompoundChangeTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRetrieveOrRequireAbscenceOfModelElement()
  {
    return retrieveOrRequireAbscenceOfModelElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRetrieveOrRequireAbscenceOfModelElement_ElementType()
  {
    return (EReference)retrieveOrRequireAbscenceOfModelElementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRetrieveOrRequireAbscenceOfModelElement_CorrespondenceSource()
  {
    return (EReference)retrieveOrRequireAbscenceOfModelElementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRetrieveOrRequireAbscenceOfModelElement_Precondition()
  {
    return (EReference)retrieveOrRequireAbscenceOfModelElementEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRequireAbscenceOfModelElement()
  {
    return requireAbscenceOfModelElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRetrieveModelElement()
  {
    return retrieveModelElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRetrieveModelElement_Name()
  {
    return (EAttribute)retrieveModelElementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRetrieveModelElement_RetrievalType()
  {
    return (EReference)retrieveModelElementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRetrieveModelElementType()
  {
    return retrieveModelElementTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMatcherCheckStatement()
  {
    return matcherCheckStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMatcherCheckStatement_Asserted()
  {
    return (EAttribute)matcherCheckStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRoutineCallStatement()
  {
    return routineCallStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExecuteActionStatement()
  {
    return executeActionStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCreateModelElement()
  {
    return createModelElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCreateModelElement_Name()
  {
    return (EAttribute)createModelElementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCreateModelElement_ElementType()
  {
    return (EReference)createModelElementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCreateModelElement_InitializationBlock()
  {
    return (EReference)createModelElementEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDeleteModelElement()
  {
    return deleteModelElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeleteModelElement_Element()
  {
    return (EReference)deleteModelElementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUpdateModelElement()
  {
    return updateModelElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUpdateModelElement_Element()
  {
    return (EReference)updateModelElementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUpdateModelElement_UpdateBlock()
  {
    return (EReference)updateModelElementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCreateCorrespondence()
  {
    return createCorrespondenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCreateCorrespondence_FirstElement()
  {
    return (EReference)createCorrespondenceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCreateCorrespondence_SecondElement()
  {
    return (EReference)createCorrespondenceEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRemoveCorrespondence()
  {
    return removeCorrespondenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRemoveCorrespondence_FirstElement()
  {
    return (EReference)removeCorrespondenceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRemoveCorrespondence_SecondElement()
  {
    return (EReference)removeCorrespondenceEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTaggable()
  {
    return taggableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTaggable_Tag()
  {
    return (EReference)taggableEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExistingElementReference()
  {
    return existingElementReferenceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTagCodeBlock()
  {
    return tagCodeBlockEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCorrespondingObjectCodeBlock()
  {
    return correspondingObjectCodeBlockEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExecutionCodeBlock()
  {
    return executionCodeBlockEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModelAttributeInsertedChange()
  {
    return modelAttributeInsertedChangeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModelAttributeRemovedChange()
  {
    return modelAttributeRemovedChangeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModelAttributeReplacedChange()
  {
    return modelAttributeReplacedChangeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRetrieveOneModelElement()
  {
    return retrieveOneModelElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRetrieveOneModelElement_Optional()
  {
    return (EAttribute)retrieveOneModelElementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRetrieveOneModelElement_Asserted()
  {
    return (EAttribute)retrieveOneModelElementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRetrieveManyModelElements()
  {
    return retrieveManyModelElementsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getRetrieveOneElementType()
  {
    return retrieveOneElementTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LanguageFactory getLanguageFactory()
  {
    return (LanguageFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    invariantViolationEventEClass = createEClass(INVARIANT_VIOLATION_EVENT);
    createEReference(invariantViolationEventEClass, INVARIANT_VIOLATION_EVENT__VIOLATION);

    modelChangeEClass = createEClass(MODEL_CHANGE);

    concreteModelChangeEClass = createEClass(CONCRETE_MODEL_CHANGE);

    modelElementChangeEClass = createEClass(MODEL_ELEMENT_CHANGE);
    createEReference(modelElementChangeEClass, MODEL_ELEMENT_CHANGE__ELEMENT_TYPE);
    createEReference(modelElementChangeEClass, MODEL_ELEMENT_CHANGE__CHANGE_TYPE);

    modelAttributeChangeEClass = createEClass(MODEL_ATTRIBUTE_CHANGE);
    createEReference(modelAttributeChangeEClass, MODEL_ATTRIBUTE_CHANGE__FEATURE);

    arbitraryModelChangeEClass = createEClass(ARBITRARY_MODEL_CHANGE);

    elementExistenceChangeTypeEClass = createEClass(ELEMENT_EXISTENCE_CHANGE_TYPE);

    modelElementUsageChangeTypeEClass = createEClass(MODEL_ELEMENT_USAGE_CHANGE_TYPE);

    elementCreationChangeTypeEClass = createEClass(ELEMENT_CREATION_CHANGE_TYPE);

    elementDeletionChangeTypeEClass = createEClass(ELEMENT_DELETION_CHANGE_TYPE);

    elementReferenceChangeTypeEClass = createEClass(ELEMENT_REFERENCE_CHANGE_TYPE);
    createEReference(elementReferenceChangeTypeEClass, ELEMENT_REFERENCE_CHANGE_TYPE__FEATURE);

    elementRootChangeTypeEClass = createEClass(ELEMENT_ROOT_CHANGE_TYPE);

    elementInsertionChangeTypeEClass = createEClass(ELEMENT_INSERTION_CHANGE_TYPE);

    elementInsertionInListChangeTypeEClass = createEClass(ELEMENT_INSERTION_IN_LIST_CHANGE_TYPE);

    elementInsertionAsRootChangeTypeEClass = createEClass(ELEMENT_INSERTION_AS_ROOT_CHANGE_TYPE);

    elementRemovalChangeTypeEClass = createEClass(ELEMENT_REMOVAL_CHANGE_TYPE);

    elementRemovalAsRootChangeTypeEClass = createEClass(ELEMENT_REMOVAL_AS_ROOT_CHANGE_TYPE);

    elementRemovalFromListChangeTypeEClass = createEClass(ELEMENT_REMOVAL_FROM_LIST_CHANGE_TYPE);

    elementReplacementChangeTypeEClass = createEClass(ELEMENT_REPLACEMENT_CHANGE_TYPE);

    elementCreationAndInsertionChangeTypeEClass = createEClass(ELEMENT_CREATION_AND_INSERTION_CHANGE_TYPE);
    createEReference(elementCreationAndInsertionChangeTypeEClass, ELEMENT_CREATION_AND_INSERTION_CHANGE_TYPE__CREATE_CHANGE);
    createEReference(elementCreationAndInsertionChangeTypeEClass, ELEMENT_CREATION_AND_INSERTION_CHANGE_TYPE__INSERT_CHANGE);

    elementDeletionAndRemovalChangeTypeEClass = createEClass(ELEMENT_DELETION_AND_REMOVAL_CHANGE_TYPE);
    createEReference(elementDeletionAndRemovalChangeTypeEClass, ELEMENT_DELETION_AND_REMOVAL_CHANGE_TYPE__DELETE_CHANGE);
    createEReference(elementDeletionAndRemovalChangeTypeEClass, ELEMENT_DELETION_AND_REMOVAL_CHANGE_TYPE__REMOVE_CHANGE);

    elementDeletionAndCreationAndReplacementChangeTypeEClass = createEClass(ELEMENT_DELETION_AND_CREATION_AND_REPLACEMENT_CHANGE_TYPE);
    createEReference(elementDeletionAndCreationAndReplacementChangeTypeEClass, ELEMENT_DELETION_AND_CREATION_AND_REPLACEMENT_CHANGE_TYPE__DELETE_CHANGE);
    createEReference(elementDeletionAndCreationAndReplacementChangeTypeEClass, ELEMENT_DELETION_AND_CREATION_AND_REPLACEMENT_CHANGE_TYPE__CREATE_CHANGE);
    createEReference(elementDeletionAndCreationAndReplacementChangeTypeEClass, ELEMENT_DELETION_AND_CREATION_AND_REPLACEMENT_CHANGE_TYPE__REPLACED_CHANGE);

    elementChangeTypeEClass = createEClass(ELEMENT_CHANGE_TYPE);

    elementCompoundChangeTypeEClass = createEClass(ELEMENT_COMPOUND_CHANGE_TYPE);

    retrieveOrRequireAbscenceOfModelElementEClass = createEClass(RETRIEVE_OR_REQUIRE_ABSCENCE_OF_MODEL_ELEMENT);
    createEReference(retrieveOrRequireAbscenceOfModelElementEClass, RETRIEVE_OR_REQUIRE_ABSCENCE_OF_MODEL_ELEMENT__ELEMENT_TYPE);
    createEReference(retrieveOrRequireAbscenceOfModelElementEClass, RETRIEVE_OR_REQUIRE_ABSCENCE_OF_MODEL_ELEMENT__CORRESPONDENCE_SOURCE);
    createEReference(retrieveOrRequireAbscenceOfModelElementEClass, RETRIEVE_OR_REQUIRE_ABSCENCE_OF_MODEL_ELEMENT__PRECONDITION);

    requireAbscenceOfModelElementEClass = createEClass(REQUIRE_ABSCENCE_OF_MODEL_ELEMENT);

    retrieveModelElementEClass = createEClass(RETRIEVE_MODEL_ELEMENT);
    createEAttribute(retrieveModelElementEClass, RETRIEVE_MODEL_ELEMENT__NAME);
    createEReference(retrieveModelElementEClass, RETRIEVE_MODEL_ELEMENT__RETRIEVAL_TYPE);

    retrieveModelElementTypeEClass = createEClass(RETRIEVE_MODEL_ELEMENT_TYPE);

    matcherCheckStatementEClass = createEClass(MATCHER_CHECK_STATEMENT);
    createEAttribute(matcherCheckStatementEClass, MATCHER_CHECK_STATEMENT__ASSERTED);

    routineCallStatementEClass = createEClass(ROUTINE_CALL_STATEMENT);

    executeActionStatementEClass = createEClass(EXECUTE_ACTION_STATEMENT);

    createModelElementEClass = createEClass(CREATE_MODEL_ELEMENT);
    createEAttribute(createModelElementEClass, CREATE_MODEL_ELEMENT__NAME);
    createEReference(createModelElementEClass, CREATE_MODEL_ELEMENT__ELEMENT_TYPE);
    createEReference(createModelElementEClass, CREATE_MODEL_ELEMENT__INITIALIZATION_BLOCK);

    deleteModelElementEClass = createEClass(DELETE_MODEL_ELEMENT);
    createEReference(deleteModelElementEClass, DELETE_MODEL_ELEMENT__ELEMENT);

    updateModelElementEClass = createEClass(UPDATE_MODEL_ELEMENT);
    createEReference(updateModelElementEClass, UPDATE_MODEL_ELEMENT__ELEMENT);
    createEReference(updateModelElementEClass, UPDATE_MODEL_ELEMENT__UPDATE_BLOCK);

    createCorrespondenceEClass = createEClass(CREATE_CORRESPONDENCE);
    createEReference(createCorrespondenceEClass, CREATE_CORRESPONDENCE__FIRST_ELEMENT);
    createEReference(createCorrespondenceEClass, CREATE_CORRESPONDENCE__SECOND_ELEMENT);

    removeCorrespondenceEClass = createEClass(REMOVE_CORRESPONDENCE);
    createEReference(removeCorrespondenceEClass, REMOVE_CORRESPONDENCE__FIRST_ELEMENT);
    createEReference(removeCorrespondenceEClass, REMOVE_CORRESPONDENCE__SECOND_ELEMENT);

    taggableEClass = createEClass(TAGGABLE);
    createEReference(taggableEClass, TAGGABLE__TAG);

    existingElementReferenceEClass = createEClass(EXISTING_ELEMENT_REFERENCE);

    tagCodeBlockEClass = createEClass(TAG_CODE_BLOCK);

    correspondingObjectCodeBlockEClass = createEClass(CORRESPONDING_OBJECT_CODE_BLOCK);

    executionCodeBlockEClass = createEClass(EXECUTION_CODE_BLOCK);

    modelAttributeInsertedChangeEClass = createEClass(MODEL_ATTRIBUTE_INSERTED_CHANGE);

    modelAttributeRemovedChangeEClass = createEClass(MODEL_ATTRIBUTE_REMOVED_CHANGE);

    modelAttributeReplacedChangeEClass = createEClass(MODEL_ATTRIBUTE_REPLACED_CHANGE);

    retrieveOneModelElementEClass = createEClass(RETRIEVE_ONE_MODEL_ELEMENT);
    createEAttribute(retrieveOneModelElementEClass, RETRIEVE_ONE_MODEL_ELEMENT__OPTIONAL);
    createEAttribute(retrieveOneModelElementEClass, RETRIEVE_ONE_MODEL_ELEMENT__ASSERTED);

    retrieveManyModelElementsEClass = createEClass(RETRIEVE_MANY_MODEL_ELEMENTS);

    // Create enums
    retrieveOneElementTypeEEnum = createEEnum(RETRIEVE_ONE_ELEMENT_TYPE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Obtain other dependent packages
    TopLevelElementsPackage theTopLevelElementsPackage = (TopLevelElementsPackage)EPackage.Registry.INSTANCE.getEPackage(TopLevelElementsPackage.eNS_URI);
    ElementsPackage theElementsPackage = (ElementsPackage)EPackage.Registry.INSTANCE.getEPackage(ElementsPackage.eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    invariantViolationEventEClass.getESuperTypes().add(theTopLevelElementsPackage.getTrigger());
    modelChangeEClass.getESuperTypes().add(theTopLevelElementsPackage.getTrigger());
    concreteModelChangeEClass.getESuperTypes().add(this.getModelChange());
    modelElementChangeEClass.getESuperTypes().add(this.getConcreteModelChange());
    modelAttributeChangeEClass.getESuperTypes().add(this.getConcreteModelChange());
    arbitraryModelChangeEClass.getESuperTypes().add(this.getModelChange());
    elementExistenceChangeTypeEClass.getESuperTypes().add(this.getElementChangeType());
    modelElementUsageChangeTypeEClass.getESuperTypes().add(this.getElementChangeType());
    elementCreationChangeTypeEClass.getESuperTypes().add(this.getElementExistenceChangeType());
    elementDeletionChangeTypeEClass.getESuperTypes().add(this.getElementExistenceChangeType());
    elementInsertionChangeTypeEClass.getESuperTypes().add(this.getModelElementUsageChangeType());
    elementInsertionInListChangeTypeEClass.getESuperTypes().add(this.getElementInsertionChangeType());
    elementInsertionInListChangeTypeEClass.getESuperTypes().add(this.getElementReferenceChangeType());
    elementInsertionAsRootChangeTypeEClass.getESuperTypes().add(this.getElementRootChangeType());
    elementInsertionAsRootChangeTypeEClass.getESuperTypes().add(this.getElementInsertionChangeType());
    elementRemovalChangeTypeEClass.getESuperTypes().add(this.getModelElementUsageChangeType());
    elementRemovalAsRootChangeTypeEClass.getESuperTypes().add(this.getElementRootChangeType());
    elementRemovalAsRootChangeTypeEClass.getESuperTypes().add(this.getElementRemovalChangeType());
    elementRemovalFromListChangeTypeEClass.getESuperTypes().add(this.getElementRemovalChangeType());
    elementRemovalFromListChangeTypeEClass.getESuperTypes().add(this.getElementReferenceChangeType());
    elementReplacementChangeTypeEClass.getESuperTypes().add(this.getModelElementUsageChangeType());
    elementReplacementChangeTypeEClass.getESuperTypes().add(this.getElementReferenceChangeType());
    elementCreationAndInsertionChangeTypeEClass.getESuperTypes().add(this.getElementCompoundChangeType());
    elementDeletionAndRemovalChangeTypeEClass.getESuperTypes().add(this.getElementCompoundChangeType());
    elementDeletionAndCreationAndReplacementChangeTypeEClass.getESuperTypes().add(this.getElementCompoundChangeType());
    elementCompoundChangeTypeEClass.getESuperTypes().add(this.getElementChangeType());
    retrieveOrRequireAbscenceOfModelElementEClass.getESuperTypes().add(theTopLevelElementsPackage.getMatcherStatement());
    retrieveOrRequireAbscenceOfModelElementEClass.getESuperTypes().add(this.getTaggable());
    requireAbscenceOfModelElementEClass.getESuperTypes().add(this.getRetrieveOrRequireAbscenceOfModelElement());
    retrieveModelElementEClass.getESuperTypes().add(this.getRetrieveOrRequireAbscenceOfModelElement());
    matcherCheckStatementEClass.getESuperTypes().add(theTopLevelElementsPackage.getMatcherStatement());
    matcherCheckStatementEClass.getESuperTypes().add(theTopLevelElementsPackage.getCodeBlock());
    routineCallStatementEClass.getESuperTypes().add(theTopLevelElementsPackage.getRoutineCallBlock());
    routineCallStatementEClass.getESuperTypes().add(theTopLevelElementsPackage.getActionStatement());
    executeActionStatementEClass.getESuperTypes().add(theTopLevelElementsPackage.getActionStatement());
    executeActionStatementEClass.getESuperTypes().add(theTopLevelElementsPackage.getCodeBlock());
    createModelElementEClass.getESuperTypes().add(theTopLevelElementsPackage.getActionStatement());
    deleteModelElementEClass.getESuperTypes().add(theTopLevelElementsPackage.getActionStatement());
    updateModelElementEClass.getESuperTypes().add(theTopLevelElementsPackage.getActionStatement());
    createCorrespondenceEClass.getESuperTypes().add(theTopLevelElementsPackage.getActionStatement());
    createCorrespondenceEClass.getESuperTypes().add(this.getTaggable());
    removeCorrespondenceEClass.getESuperTypes().add(theTopLevelElementsPackage.getActionStatement());
    removeCorrespondenceEClass.getESuperTypes().add(this.getTaggable());
    existingElementReferenceEClass.getESuperTypes().add(theTopLevelElementsPackage.getCodeBlock());
    tagCodeBlockEClass.getESuperTypes().add(theTopLevelElementsPackage.getCodeBlock());
    correspondingObjectCodeBlockEClass.getESuperTypes().add(theTopLevelElementsPackage.getCodeBlock());
    executionCodeBlockEClass.getESuperTypes().add(theTopLevelElementsPackage.getCodeBlock());
    modelAttributeInsertedChangeEClass.getESuperTypes().add(this.getModelAttributeChange());
    modelAttributeRemovedChangeEClass.getESuperTypes().add(this.getModelAttributeChange());
    modelAttributeReplacedChangeEClass.getESuperTypes().add(this.getModelAttributeChange());
    retrieveOneModelElementEClass.getESuperTypes().add(this.getRetrieveModelElementType());
    retrieveManyModelElementsEClass.getESuperTypes().add(this.getRetrieveModelElementType());

    // Initialize classes and features; add operations and parameters
    initEClass(invariantViolationEventEClass, InvariantViolationEvent.class, "InvariantViolationEvent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getInvariantViolationEvent_Violation(), ecorePackage.getEClass(), null, "violation", null, 0, 1, InvariantViolationEvent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(modelChangeEClass, ModelChange.class, "ModelChange", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(concreteModelChangeEClass, ConcreteModelChange.class, "ConcreteModelChange", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(modelElementChangeEClass, ModelElementChange.class, "ModelElementChange", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModelElementChange_ElementType(), theElementsPackage.getMetaclassReference(), null, "elementType", null, 0, 1, ModelElementChange.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModelElementChange_ChangeType(), this.getElementChangeType(), null, "changeType", null, 0, 1, ModelElementChange.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(modelAttributeChangeEClass, ModelAttributeChange.class, "ModelAttributeChange", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModelAttributeChange_Feature(), theElementsPackage.getMetaclassEAttributeReference(), null, "feature", null, 0, 1, ModelAttributeChange.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(arbitraryModelChangeEClass, ArbitraryModelChange.class, "ArbitraryModelChange", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(elementExistenceChangeTypeEClass, ElementExistenceChangeType.class, "ElementExistenceChangeType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(modelElementUsageChangeTypeEClass, ModelElementUsageChangeType.class, "ModelElementUsageChangeType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(elementCreationChangeTypeEClass, ElementCreationChangeType.class, "ElementCreationChangeType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(elementDeletionChangeTypeEClass, ElementDeletionChangeType.class, "ElementDeletionChangeType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(elementReferenceChangeTypeEClass, ElementReferenceChangeType.class, "ElementReferenceChangeType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getElementReferenceChangeType_Feature(), theElementsPackage.getMetaclassEReferenceReference(), null, "feature", null, 0, 1, ElementReferenceChangeType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(elementRootChangeTypeEClass, ElementRootChangeType.class, "ElementRootChangeType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(elementInsertionChangeTypeEClass, ElementInsertionChangeType.class, "ElementInsertionChangeType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(elementInsertionInListChangeTypeEClass, ElementInsertionInListChangeType.class, "ElementInsertionInListChangeType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(elementInsertionAsRootChangeTypeEClass, ElementInsertionAsRootChangeType.class, "ElementInsertionAsRootChangeType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(elementRemovalChangeTypeEClass, ElementRemovalChangeType.class, "ElementRemovalChangeType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(elementRemovalAsRootChangeTypeEClass, ElementRemovalAsRootChangeType.class, "ElementRemovalAsRootChangeType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(elementRemovalFromListChangeTypeEClass, ElementRemovalFromListChangeType.class, "ElementRemovalFromListChangeType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(elementReplacementChangeTypeEClass, ElementReplacementChangeType.class, "ElementReplacementChangeType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(elementCreationAndInsertionChangeTypeEClass, ElementCreationAndInsertionChangeType.class, "ElementCreationAndInsertionChangeType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getElementCreationAndInsertionChangeType_CreateChange(), this.getElementCreationChangeType(), null, "createChange", null, 0, 1, ElementCreationAndInsertionChangeType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getElementCreationAndInsertionChangeType_InsertChange(), this.getElementInsertionChangeType(), null, "insertChange", null, 0, 1, ElementCreationAndInsertionChangeType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(elementDeletionAndRemovalChangeTypeEClass, ElementDeletionAndRemovalChangeType.class, "ElementDeletionAndRemovalChangeType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getElementDeletionAndRemovalChangeType_DeleteChange(), this.getElementDeletionChangeType(), null, "deleteChange", null, 0, 1, ElementDeletionAndRemovalChangeType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getElementDeletionAndRemovalChangeType_RemoveChange(), this.getElementRemovalChangeType(), null, "removeChange", null, 0, 1, ElementDeletionAndRemovalChangeType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(elementDeletionAndCreationAndReplacementChangeTypeEClass, ElementDeletionAndCreationAndReplacementChangeType.class, "ElementDeletionAndCreationAndReplacementChangeType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getElementDeletionAndCreationAndReplacementChangeType_DeleteChange(), this.getElementDeletionChangeType(), null, "deleteChange", null, 0, 1, ElementDeletionAndCreationAndReplacementChangeType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getElementDeletionAndCreationAndReplacementChangeType_CreateChange(), this.getElementCreationChangeType(), null, "createChange", null, 0, 1, ElementDeletionAndCreationAndReplacementChangeType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getElementDeletionAndCreationAndReplacementChangeType_ReplacedChange(), this.getElementReplacementChangeType(), null, "replacedChange", null, 0, 1, ElementDeletionAndCreationAndReplacementChangeType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(elementChangeTypeEClass, ElementChangeType.class, "ElementChangeType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(elementCompoundChangeTypeEClass, ElementCompoundChangeType.class, "ElementCompoundChangeType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(retrieveOrRequireAbscenceOfModelElementEClass, RetrieveOrRequireAbscenceOfModelElement.class, "RetrieveOrRequireAbscenceOfModelElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRetrieveOrRequireAbscenceOfModelElement_ElementType(), theElementsPackage.getMetaclassReference(), null, "elementType", null, 0, 1, RetrieveOrRequireAbscenceOfModelElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRetrieveOrRequireAbscenceOfModelElement_CorrespondenceSource(), this.getCorrespondingObjectCodeBlock(), null, "correspondenceSource", null, 0, 1, RetrieveOrRequireAbscenceOfModelElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRetrieveOrRequireAbscenceOfModelElement_Precondition(), theTopLevelElementsPackage.getPreconditionCodeBlock(), null, "precondition", null, 0, 1, RetrieveOrRequireAbscenceOfModelElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(requireAbscenceOfModelElementEClass, RequireAbscenceOfModelElement.class, "RequireAbscenceOfModelElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(retrieveModelElementEClass, RetrieveModelElement.class, "RetrieveModelElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRetrieveModelElement_Name(), ecorePackage.getEString(), "name", null, 0, 1, RetrieveModelElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRetrieveModelElement_RetrievalType(), this.getRetrieveModelElementType(), null, "retrievalType", null, 0, 1, RetrieveModelElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(retrieveModelElementTypeEClass, RetrieveModelElementType.class, "RetrieveModelElementType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(matcherCheckStatementEClass, MatcherCheckStatement.class, "MatcherCheckStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMatcherCheckStatement_Asserted(), ecorePackage.getEBoolean(), "asserted", null, 0, 1, MatcherCheckStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(routineCallStatementEClass, RoutineCallStatement.class, "RoutineCallStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(executeActionStatementEClass, ExecuteActionStatement.class, "ExecuteActionStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(createModelElementEClass, CreateModelElement.class, "CreateModelElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCreateModelElement_Name(), ecorePackage.getEString(), "name", null, 0, 1, CreateModelElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCreateModelElement_ElementType(), theElementsPackage.getMetaclassReference(), null, "elementType", null, 0, 1, CreateModelElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCreateModelElement_InitializationBlock(), this.getExecutionCodeBlock(), null, "initializationBlock", null, 0, 1, CreateModelElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(deleteModelElementEClass, DeleteModelElement.class, "DeleteModelElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDeleteModelElement_Element(), this.getExistingElementReference(), null, "element", null, 0, 1, DeleteModelElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(updateModelElementEClass, UpdateModelElement.class, "UpdateModelElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getUpdateModelElement_Element(), this.getExistingElementReference(), null, "element", null, 0, 1, UpdateModelElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUpdateModelElement_UpdateBlock(), this.getExecutionCodeBlock(), null, "updateBlock", null, 0, 1, UpdateModelElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(createCorrespondenceEClass, CreateCorrespondence.class, "CreateCorrespondence", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCreateCorrespondence_FirstElement(), this.getExistingElementReference(), null, "firstElement", null, 0, 1, CreateCorrespondence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCreateCorrespondence_SecondElement(), this.getExistingElementReference(), null, "secondElement", null, 0, 1, CreateCorrespondence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(removeCorrespondenceEClass, RemoveCorrespondence.class, "RemoveCorrespondence", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRemoveCorrespondence_FirstElement(), this.getExistingElementReference(), null, "firstElement", null, 0, 1, RemoveCorrespondence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRemoveCorrespondence_SecondElement(), this.getExistingElementReference(), null, "secondElement", null, 0, 1, RemoveCorrespondence.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(taggableEClass, Taggable.class, "Taggable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getTaggable_Tag(), this.getTagCodeBlock(), null, "tag", null, 0, 1, Taggable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(existingElementReferenceEClass, ExistingElementReference.class, "ExistingElementReference", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(tagCodeBlockEClass, TagCodeBlock.class, "TagCodeBlock", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(correspondingObjectCodeBlockEClass, CorrespondingObjectCodeBlock.class, "CorrespondingObjectCodeBlock", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(executionCodeBlockEClass, ExecutionCodeBlock.class, "ExecutionCodeBlock", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(modelAttributeInsertedChangeEClass, ModelAttributeInsertedChange.class, "ModelAttributeInsertedChange", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(modelAttributeRemovedChangeEClass, ModelAttributeRemovedChange.class, "ModelAttributeRemovedChange", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(modelAttributeReplacedChangeEClass, ModelAttributeReplacedChange.class, "ModelAttributeReplacedChange", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(retrieveOneModelElementEClass, RetrieveOneModelElement.class, "RetrieveOneModelElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRetrieveOneModelElement_Optional(), ecorePackage.getEBoolean(), "optional", null, 0, 1, RetrieveOneModelElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRetrieveOneModelElement_Asserted(), ecorePackage.getEBoolean(), "asserted", null, 0, 1, RetrieveOneModelElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(retrieveManyModelElementsEClass, RetrieveManyModelElements.class, "RetrieveManyModelElements", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    // Initialize enums and add enum literals
    initEEnum(retrieveOneElementTypeEEnum, RetrieveOneElementType.class, "RetrieveOneElementType");
    addEEnumLiteral(retrieveOneElementTypeEEnum, RetrieveOneElementType.OPTIONAL);
    addEEnumLiteral(retrieveOneElementTypeEEnum, RetrieveOneElementType.ASSERTED);

    // Create resource
    createResource(eNS_URI);
  }

} //LanguagePackageImpl
