/**
 * generated by Xtext 2.24.0
 */
package tools.vitruv.dsls.reactions.language.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.xtext.xbase.XExpression;

import tools.vitruv.dsls.reactions.language.LanguagePackage;
import tools.vitruv.dsls.reactions.language.MatcherCheckStatement;

import tools.vitruv.dsls.reactions.language.toplevelelements.CodeBlock;
import tools.vitruv.dsls.reactions.language.toplevelelements.TopLevelElementsPackage;

import tools.vitruv.dsls.reactions.language.toplevelelements.impl.MatcherStatementImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Matcher Check Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.reactions.language.impl.MatcherCheckStatementImpl#getCode <em>Code</em>}</li>
 *   <li>{@link tools.vitruv.dsls.reactions.language.impl.MatcherCheckStatementImpl#isAsserted <em>Asserted</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MatcherCheckStatementImpl extends MatcherStatementImpl implements MatcherCheckStatement
{
  /**
   * The cached value of the '{@link #getCode() <em>Code</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCode()
   * @generated
   * @ordered
   */
  protected XExpression code;

  /**
   * The default value of the '{@link #isAsserted() <em>Asserted</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isAsserted()
   * @generated
   * @ordered
   */
  protected static final boolean ASSERTED_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isAsserted() <em>Asserted</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isAsserted()
   * @generated
   * @ordered
   */
  protected boolean asserted = ASSERTED_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MatcherCheckStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LanguagePackage.Literals.MATCHER_CHECK_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public XExpression getCode()
  {
    return code;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCode(XExpression newCode, NotificationChain msgs)
  {
    XExpression oldCode = code;
    code = newCode;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LanguagePackage.MATCHER_CHECK_STATEMENT__CODE, oldCode, newCode);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCode(XExpression newCode)
  {
    if (newCode != code)
    {
      NotificationChain msgs = null;
      if (code != null)
        msgs = ((InternalEObject)code).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LanguagePackage.MATCHER_CHECK_STATEMENT__CODE, null, msgs);
      if (newCode != null)
        msgs = ((InternalEObject)newCode).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LanguagePackage.MATCHER_CHECK_STATEMENT__CODE, null, msgs);
      msgs = basicSetCode(newCode, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LanguagePackage.MATCHER_CHECK_STATEMENT__CODE, newCode, newCode));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isAsserted()
  {
    return asserted;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAsserted(boolean newAsserted)
  {
    boolean oldAsserted = asserted;
    asserted = newAsserted;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LanguagePackage.MATCHER_CHECK_STATEMENT__ASSERTED, oldAsserted, asserted));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LanguagePackage.MATCHER_CHECK_STATEMENT__CODE:
        return basicSetCode(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LanguagePackage.MATCHER_CHECK_STATEMENT__CODE:
        return getCode();
      case LanguagePackage.MATCHER_CHECK_STATEMENT__ASSERTED:
        return isAsserted();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LanguagePackage.MATCHER_CHECK_STATEMENT__CODE:
        setCode((XExpression)newValue);
        return;
      case LanguagePackage.MATCHER_CHECK_STATEMENT__ASSERTED:
        setAsserted((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LanguagePackage.MATCHER_CHECK_STATEMENT__CODE:
        setCode((XExpression)null);
        return;
      case LanguagePackage.MATCHER_CHECK_STATEMENT__ASSERTED:
        setAsserted(ASSERTED_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LanguagePackage.MATCHER_CHECK_STATEMENT__CODE:
        return code != null;
      case LanguagePackage.MATCHER_CHECK_STATEMENT__ASSERTED:
        return asserted != ASSERTED_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eBaseStructuralFeatureID(int derivedFeatureID, Class<?> baseClass)
  {
    if (baseClass == CodeBlock.class)
    {
      switch (derivedFeatureID)
      {
        case LanguagePackage.MATCHER_CHECK_STATEMENT__CODE: return TopLevelElementsPackage.CODE_BLOCK__CODE;
        default: return -1;
      }
    }
    return super.eBaseStructuralFeatureID(derivedFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eDerivedStructuralFeatureID(int baseFeatureID, Class<?> baseClass)
  {
    if (baseClass == CodeBlock.class)
    {
      switch (baseFeatureID)
      {
        case TopLevelElementsPackage.CODE_BLOCK__CODE: return LanguagePackage.MATCHER_CHECK_STATEMENT__CODE;
        default: return -1;
      }
    }
    return super.eDerivedStructuralFeatureID(baseFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (asserted: ");
    result.append(asserted);
    result.append(')');
    return result.toString();
  }

} //MatcherCheckStatementImpl
