/**
 * generated by Xtext 2.24.0
 */
package tools.vitruv.dsls.reactions.language.impl;

import org.eclipse.emf.ecore.EClass;

import tools.vitruv.dsls.reactions.language.LanguagePackage;
import tools.vitruv.dsls.reactions.language.ModelChange;

import tools.vitruv.dsls.reactions.language.toplevelelements.impl.TriggerImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Model Change</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ModelChangeImpl extends TriggerImpl implements ModelChange
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModelChangeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LanguagePackage.Literals.MODEL_CHANGE;
  }

} //ModelChangeImpl
