/**
 * generated by Xtext 2.24.0
 */
package tools.vitruv.dsls.reactions.language.impl;

import org.eclipse.emf.ecore.EClass;

import tools.vitruv.dsls.reactions.language.LanguagePackage;
import tools.vitruv.dsls.reactions.language.RoutineCallStatement;

import tools.vitruv.dsls.reactions.language.toplevelelements.impl.RoutineCallBlockImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Routine Call Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RoutineCallStatementImpl extends RoutineCallBlockImpl implements RoutineCallStatement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RoutineCallStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LanguagePackage.Literals.ROUTINE_CALL_STATEMENT;
  }

} //RoutineCallStatementImpl
