/**
 * generated by Xtext 2.24.0
 */
package tools.vitruv.dsls.reactions.language;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Arbitrary Model Change</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getArbitraryModelChange()
 * @model
 * @generated
 */
public interface ArbitraryModelChange extends ModelChange
{
} // ArbitraryModelChange
