/**
 * generated by Xtext 2.24.0
 */
package tools.vitruv.dsls.reactions.language;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Concrete Model Change</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getConcreteModelChange()
 * @model
 * @generated
 */
public interface ConcreteModelChange extends ModelChange
{
} // ConcreteModelChange
