/**
 * generated by Xtext 2.24.0
 */
package tools.vitruv.dsls.reactions.language;

import tools.vitruv.dsls.reactions.language.toplevelelements.ActionStatement;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Create Correspondence</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.reactions.language.CreateCorrespondence#getFirstElement <em>First Element</em>}</li>
 *   <li>{@link tools.vitruv.dsls.reactions.language.CreateCorrespondence#getSecondElement <em>Second Element</em>}</li>
 * </ul>
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getCreateCorrespondence()
 * @model
 * @generated
 */
public interface CreateCorrespondence extends ActionStatement, Taggable
{
  /**
   * Returns the value of the '<em><b>First Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>First Element</em>' containment reference.
   * @see #setFirstElement(ExistingElementReference)
   * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getCreateCorrespondence_FirstElement()
   * @model containment="true"
   * @generated
   */
  ExistingElementReference getFirstElement();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.reactions.language.CreateCorrespondence#getFirstElement <em>First Element</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>First Element</em>' containment reference.
   * @see #getFirstElement()
   * @generated
   */
  void setFirstElement(ExistingElementReference value);

  /**
   * Returns the value of the '<em><b>Second Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Second Element</em>' containment reference.
   * @see #setSecondElement(ExistingElementReference)
   * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getCreateCorrespondence_SecondElement()
   * @model containment="true"
   * @generated
   */
  ExistingElementReference getSecondElement();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.reactions.language.CreateCorrespondence#getSecondElement <em>Second Element</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Second Element</em>' containment reference.
   * @see #getSecondElement()
   * @generated
   */
  void setSecondElement(ExistingElementReference value);

} // CreateCorrespondence
