/**
 * generated by Xtext 2.24.0
 */
package tools.vitruv.dsls.reactions.language;

import tools.vitruv.dsls.common.elements.MetaclassReference;

import tools.vitruv.dsls.reactions.language.toplevelelements.ActionStatement;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Create Model Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.reactions.language.CreateModelElement#getName <em>Name</em>}</li>
 *   <li>{@link tools.vitruv.dsls.reactions.language.CreateModelElement#getElementType <em>Element Type</em>}</li>
 *   <li>{@link tools.vitruv.dsls.reactions.language.CreateModelElement#getInitializationBlock <em>Initialization Block</em>}</li>
 * </ul>
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getCreateModelElement()
 * @model
 * @generated
 */
public interface CreateModelElement extends ActionStatement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getCreateModelElement_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.reactions.language.CreateModelElement#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Element Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element Type</em>' containment reference.
   * @see #setElementType(MetaclassReference)
   * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getCreateModelElement_ElementType()
   * @model containment="true"
   * @generated
   */
  MetaclassReference getElementType();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.reactions.language.CreateModelElement#getElementType <em>Element Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element Type</em>' containment reference.
   * @see #getElementType()
   * @generated
   */
  void setElementType(MetaclassReference value);

  /**
   * Returns the value of the '<em><b>Initialization Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initialization Block</em>' containment reference.
   * @see #setInitializationBlock(ExecutionCodeBlock)
   * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getCreateModelElement_InitializationBlock()
   * @model containment="true"
   * @generated
   */
  ExecutionCodeBlock getInitializationBlock();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.reactions.language.CreateModelElement#getInitializationBlock <em>Initialization Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Initialization Block</em>' containment reference.
   * @see #getInitializationBlock()
   * @generated
   */
  void setInitializationBlock(ExecutionCodeBlock value);

} // CreateModelElement
