/**
 * generated by Xtext 2.24.0
 */
package tools.vitruv.dsls.reactions.language;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element Deletion And Creation And Replacement Change Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.reactions.language.ElementDeletionAndCreationAndReplacementChangeType#getDeleteChange <em>Delete Change</em>}</li>
 *   <li>{@link tools.vitruv.dsls.reactions.language.ElementDeletionAndCreationAndReplacementChangeType#getCreateChange <em>Create Change</em>}</li>
 *   <li>{@link tools.vitruv.dsls.reactions.language.ElementDeletionAndCreationAndReplacementChangeType#getReplacedChange <em>Replaced Change</em>}</li>
 * </ul>
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getElementDeletionAndCreationAndReplacementChangeType()
 * @model
 * @generated
 */
public interface ElementDeletionAndCreationAndReplacementChangeType extends ElementCompoundChangeType
{
  /**
   * Returns the value of the '<em><b>Delete Change</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Delete Change</em>' containment reference.
   * @see #setDeleteChange(ElementDeletionChangeType)
   * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getElementDeletionAndCreationAndReplacementChangeType_DeleteChange()
   * @model containment="true"
   * @generated
   */
  ElementDeletionChangeType getDeleteChange();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.reactions.language.ElementDeletionAndCreationAndReplacementChangeType#getDeleteChange <em>Delete Change</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Delete Change</em>' containment reference.
   * @see #getDeleteChange()
   * @generated
   */
  void setDeleteChange(ElementDeletionChangeType value);

  /**
   * Returns the value of the '<em><b>Create Change</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Create Change</em>' containment reference.
   * @see #setCreateChange(ElementCreationChangeType)
   * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getElementDeletionAndCreationAndReplacementChangeType_CreateChange()
   * @model containment="true"
   * @generated
   */
  ElementCreationChangeType getCreateChange();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.reactions.language.ElementDeletionAndCreationAndReplacementChangeType#getCreateChange <em>Create Change</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Create Change</em>' containment reference.
   * @see #getCreateChange()
   * @generated
   */
  void setCreateChange(ElementCreationChangeType value);

  /**
   * Returns the value of the '<em><b>Replaced Change</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Replaced Change</em>' containment reference.
   * @see #setReplacedChange(ElementReplacementChangeType)
   * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getElementDeletionAndCreationAndReplacementChangeType_ReplacedChange()
   * @model containment="true"
   * @generated
   */
  ElementReplacementChangeType getReplacedChange();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.reactions.language.ElementDeletionAndCreationAndReplacementChangeType#getReplacedChange <em>Replaced Change</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Replaced Change</em>' containment reference.
   * @see #getReplacedChange()
   * @generated
   */
  void setReplacedChange(ElementReplacementChangeType value);

} // ElementDeletionAndCreationAndReplacementChangeType
