/**
 * generated by Xtext 2.24.0
 */
package tools.vitruv.dsls.reactions.language;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element Compound Change Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getElementCompoundChangeType()
 * @model
 * @generated
 */
public interface ElementCompoundChangeType extends ElementChangeType
{
} // ElementCompoundChangeType
