/**
 * generated by Xtext 2.24.0
 */
package tools.vitruv.dsls.reactions.language;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element Deletion And Removal Change Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.reactions.language.ElementDeletionAndRemovalChangeType#getDeleteChange <em>Delete Change</em>}</li>
 *   <li>{@link tools.vitruv.dsls.reactions.language.ElementDeletionAndRemovalChangeType#getRemoveChange <em>Remove Change</em>}</li>
 * </ul>
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getElementDeletionAndRemovalChangeType()
 * @model
 * @generated
 */
public interface ElementDeletionAndRemovalChangeType extends ElementCompoundChangeType
{
  /**
   * Returns the value of the '<em><b>Delete Change</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Delete Change</em>' containment reference.
   * @see #setDeleteChange(ElementDeletionChangeType)
   * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getElementDeletionAndRemovalChangeType_DeleteChange()
   * @model containment="true"
   * @generated
   */
  ElementDeletionChangeType getDeleteChange();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.reactions.language.ElementDeletionAndRemovalChangeType#getDeleteChange <em>Delete Change</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Delete Change</em>' containment reference.
   * @see #getDeleteChange()
   * @generated
   */
  void setDeleteChange(ElementDeletionChangeType value);

  /**
   * Returns the value of the '<em><b>Remove Change</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Remove Change</em>' containment reference.
   * @see #setRemoveChange(ElementRemovalChangeType)
   * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getElementDeletionAndRemovalChangeType_RemoveChange()
   * @model containment="true"
   * @generated
   */
  ElementRemovalChangeType getRemoveChange();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.reactions.language.ElementDeletionAndRemovalChangeType#getRemoveChange <em>Remove Change</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Remove Change</em>' containment reference.
   * @see #getRemoveChange()
   * @generated
   */
  void setRemoveChange(ElementRemovalChangeType value);

} // ElementDeletionAndRemovalChangeType
