/**
 * generated by Xtext 2.24.0
 */
package tools.vitruv.dsls.reactions.language;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element Insertion Change Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getElementInsertionChangeType()
 * @model
 * @generated
 */
public interface ElementInsertionChangeType extends ModelElementUsageChangeType
{
} // ElementInsertionChangeType
