/**
 * generated by Xtext 2.24.0
 */
package tools.vitruv.dsls.reactions.language;

import tools.vitruv.dsls.reactions.language.toplevelelements.ActionStatement;
import tools.vitruv.dsls.reactions.language.toplevelelements.CodeBlock;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Execute Action Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getExecuteActionStatement()
 * @model
 * @generated
 */
public interface ExecuteActionStatement extends ActionStatement, CodeBlock
{
} // ExecuteActionStatement
