/**
 * generated by Xtext 2.24.0
 */
package tools.vitruv.dsls.reactions.language;

import tools.vitruv.dsls.reactions.language.toplevelelements.CodeBlock;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Existing Element Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getExistingElementReference()
 * @model
 * @generated
 */
public interface ExistingElementReference extends CodeBlock
{
} // ExistingElementReference
