/**
 * generated by Xtext 2.24.0
 */
package tools.vitruv.dsls.reactions.language;

import tools.vitruv.dsls.reactions.language.toplevelelements.CodeBlock;
import tools.vitruv.dsls.reactions.language.toplevelelements.MatcherStatement;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Matcher Check Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.reactions.language.MatcherCheckStatement#isAsserted <em>Asserted</em>}</li>
 * </ul>
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getMatcherCheckStatement()
 * @model
 * @generated
 */
public interface MatcherCheckStatement extends MatcherStatement, CodeBlock
{
  /**
   * Returns the value of the '<em><b>Asserted</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Asserted</em>' attribute.
   * @see #setAsserted(boolean)
   * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getMatcherCheckStatement_Asserted()
   * @model
   * @generated
   */
  boolean isAsserted();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.reactions.language.MatcherCheckStatement#isAsserted <em>Asserted</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Asserted</em>' attribute.
   * @see #isAsserted()
   * @generated
   */
  void setAsserted(boolean value);

} // MatcherCheckStatement
