/**
 * generated by Xtext 2.24.0
 */
package tools.vitruv.dsls.reactions.language;

import tools.vitruv.dsls.reactions.language.toplevelelements.Trigger;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model Change</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getModelChange()
 * @model
 * @generated
 */
public interface ModelChange extends Trigger
{
} // ModelChange
