/**
 * generated by Xtext 2.24.0
 */
package tools.vitruv.dsls.reactions.language;

import tools.vitruv.dsls.common.elements.MetaclassReference;

import tools.vitruv.dsls.reactions.language.toplevelelements.MatcherStatement;
import tools.vitruv.dsls.reactions.language.toplevelelements.PreconditionCodeBlock;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Retrieve Or Require Abscence Of Model Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tools.vitruv.dsls.reactions.language.RetrieveOrRequireAbscenceOfModelElement#getElementType <em>Element Type</em>}</li>
 *   <li>{@link tools.vitruv.dsls.reactions.language.RetrieveOrRequireAbscenceOfModelElement#getCorrespondenceSource <em>Correspondence Source</em>}</li>
 *   <li>{@link tools.vitruv.dsls.reactions.language.RetrieveOrRequireAbscenceOfModelElement#getPrecondition <em>Precondition</em>}</li>
 * </ul>
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getRetrieveOrRequireAbscenceOfModelElement()
 * @model
 * @generated
 */
public interface RetrieveOrRequireAbscenceOfModelElement extends MatcherStatement, Taggable
{
  /**
   * Returns the value of the '<em><b>Element Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element Type</em>' containment reference.
   * @see #setElementType(MetaclassReference)
   * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getRetrieveOrRequireAbscenceOfModelElement_ElementType()
   * @model containment="true"
   * @generated
   */
  MetaclassReference getElementType();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.reactions.language.RetrieveOrRequireAbscenceOfModelElement#getElementType <em>Element Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element Type</em>' containment reference.
   * @see #getElementType()
   * @generated
   */
  void setElementType(MetaclassReference value);

  /**
   * Returns the value of the '<em><b>Correspondence Source</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Correspondence Source</em>' containment reference.
   * @see #setCorrespondenceSource(CorrespondingObjectCodeBlock)
   * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getRetrieveOrRequireAbscenceOfModelElement_CorrespondenceSource()
   * @model containment="true"
   * @generated
   */
  CorrespondingObjectCodeBlock getCorrespondenceSource();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.reactions.language.RetrieveOrRequireAbscenceOfModelElement#getCorrespondenceSource <em>Correspondence Source</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Correspondence Source</em>' containment reference.
   * @see #getCorrespondenceSource()
   * @generated
   */
  void setCorrespondenceSource(CorrespondingObjectCodeBlock value);

  /**
   * Returns the value of the '<em><b>Precondition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Precondition</em>' containment reference.
   * @see #setPrecondition(PreconditionCodeBlock)
   * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getRetrieveOrRequireAbscenceOfModelElement_Precondition()
   * @model containment="true"
   * @generated
   */
  PreconditionCodeBlock getPrecondition();

  /**
   * Sets the value of the '{@link tools.vitruv.dsls.reactions.language.RetrieveOrRequireAbscenceOfModelElement#getPrecondition <em>Precondition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Precondition</em>' containment reference.
   * @see #getPrecondition()
   * @generated
   */
  void setPrecondition(PreconditionCodeBlock value);

} // RetrieveOrRequireAbscenceOfModelElement
