/**
 * generated by Xtext 2.24.0
 */
package tools.vitruv.dsls.reactions.language;

import tools.vitruv.dsls.reactions.language.toplevelelements.ActionStatement;
import tools.vitruv.dsls.reactions.language.toplevelelements.RoutineCallBlock;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Routine Call Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getRoutineCallStatement()
 * @model
 * @generated
 */
public interface RoutineCallStatement extends RoutineCallBlock, ActionStatement
{
} // RoutineCallStatement
