/**
 * generated by Xtext 2.24.0
 */
package tools.vitruv.dsls.reactions.language;

import tools.vitruv.dsls.reactions.language.toplevelelements.CodeBlock;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tag Code Block</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tools.vitruv.dsls.reactions.language.LanguagePackage#getTagCodeBlock()
 * @model
 * @generated
 */
public interface TagCodeBlock extends CodeBlock
{
} // TagCodeBlock
